### PR TITLE
NO-REF: Bump mermaid to 6.0.0

### PR DESCRIPTION
**Pull request by cluePrints**
This bumps mermaid to higher major version to be compatible with the docs and be less buggy in general.

### CODE REVIEW

**Comment by chriswessels** [comment]
Thanks @cluePrints!

**Comment by yegor-qwerty** [comment]
@chriswessels, thanks for merging it. Could you please release it on NPM? So everyone could get those changes within GitbookPlugin.

Thanks.

**Comment by chriswessels** [comment]
@sigarev Done!

**Comment by yegor-qwerty** [comment]
@chriswessels, thank you so much for super quick repose. We will check and let you know results.

**Comment by cluePrints** [comment]
@chriswessels thank you for the quick merge :)

**Comment by yegor-qwerty** [comment]
@chriswessels, we checked new release and it works perfect. Thanks.

**Comment by chriswessels** [comment]
@sigarev @cluePrints No problem, thanks again for the PR.

**Pull request merged**
